### ISSUE TITLE
bug: 'obj' is undefined

### ISSUE THREAD

**Issue by michprev** [mkdocstrings/python#127]
### Description of the bug
The version 1.8.0 introduced an issue in my project when building the docs fails with `jinja2.exceptions.UndefinedError: 'obj' is undefined`. I assume this is a problem with incompatible dependencies.

### To Reproduce
Probably depends on the versions of installed dependencies.
Some of the versions of dependencies:
```
mkdocstrings-python: 1.8.0
mkdocstrings: 0.24.0
mkdocs: 1.5.3
griffe: 0.39.1
jinja2: 3.1.2
```

I can currently reproduce this in my project:
```
git clone https://github.com/Ackee-Blockchain/wake.git && cd wake
python -m pip install -e ".[dev]"
mkdocs serve
```

### Full traceback

<details><summary>Full traceback</summary>

```python
Traceback (most recent call last):
  File "/home/michal/.pyenv/versions/3.11.4/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocs/commands/build.py", line 175, in _populate_page
    page.render(config, files)
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocs/structure/pages.py", line 271, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.local/lib/python3.11/site-packages/markdown/core.py", line 254, in convert
    root = self.parser.parseDocument(self.lines).getroot()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.local/lib/python3.11/site-packages/markdown/blockparser.py", line 84, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "/home/michal/.local/lib/python3.11/site-packages/markdown/blockparser.py", line 99, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "/home/michal/.local/lib/python3.11/site-packages/markdown/blockparser.py", line 117, in parseBlocks
    if processor.run(parent, blocks) is not False:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocstrings/extension.py", line 124, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocstrings/extension.py", line 220, in _process_block
    rendered = handler.render(data, options)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocstrings_handlers/python/handler.py", line 355, in render
    return template.render(
           ^^^^^^^^^^^^^^^^
  File "/home/michal/.local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/michal/.local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/michal/git/wake/docs/templates/python/material/class.html", line 78, in top-level template code
    {% include "docstring.html" with context %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/docstring.html", line 1, in top-level template code
    {% extends "_base/docstring.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/docstring.html", line 7, in top-level template code
    {% include "docstring/attributes.html" with context %}
^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/docstring/attributes.html", line 1, in top-level template code
    {% extends "_base/docstring/attributes.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/docstring/attributes.html", line 6, in top-level template code
    {% block table_style %}
  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.pyenv/versions/3.11.4/lib/python3.11/site-packages/mkdocstrings_handlers/python/templates/material/_base/docstring/attributes.html", line 19, in block 'table_style'
    <td><code><span data-autorefs-optional-hover="{{ obj.path }}.{{ attribute.name }}">{{ attribute.name }}</span></code></td>
^^^^^^^^^^^^^^^^^^^
  File "/home/michal/.local/lib/python3.11/site-packages/jinja2/environment.py", line 485, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'obj' is undefined
```

</details>

### Expected behavior

The documentation generation wouldn't crash.

### Environment information

```bash
- __System__: Linux-6.6.13-200.fc39.x86_64-x86_64-with-glibc2.38
- __Python__: cpython 3.11.4
- __Environment variables__:
- __Installed packages__:
  - `mkdocs` v1.5.3
  - `mkdocstrings` v0.24.0
  - `mkdocstrings-python` v1.8.0
  - `griffe` v0.39.1
```

**Comment by pawamoy** [comment]
Hello, thanks for the report! It seems your custom templates are not up to date with the ones from 1.8.0:

- In `class.html`, line 4, try: `{% with obj = class, html_id = class.path %}`
- In `module.html`, line 4, try: `{% with obj = module, html_id = module.path %}`

Even better: you can now override just parts of the templates thanks to the recent addition of Jinja blocks. See https://mkdocstrings.github.io/python/usage/customization/#available-blocks. If you tell me what part you customized, I can provide more guidance :slightly_smiling_face: 

Closing but we can continue our discussion!

**Comment by michprev** [comment]
Hi @pawamoy, thank you for your guidance! I can confirm the issue was in our outdated templates.

I completely forgot we're using custom templates. Customizable blocks in templates look cool, will definitely check them out.
