### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by hgue** [mkdocstrings/python#50]
Hello,
I have problems in generating documentation from python module. It says that module was not found for importing.
However I am not sure where to search further.

python 3.9.12
mkdocs=1.4.2
mkdocstrings=0.19.1
mkdocstrings-python=0.8.3

Can anyone point me in the right direction here?

ERROR    -  Error reading page 'libs/iot/azure/azure_device_client.md': Empty module name
Traceback (most recent call last):
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\griffe\loader.py", line 139, in load_module
    module_name, package = self.finder.find_spec(module, try_relative_path)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\griffe\finder.py", line 119, in find_spec
    return module_name, self.find_package(top_module_name)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\griffe\finder.py", line 159, in find_package
    raise ModuleNotFoundError(module_name)
ModuleNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\mkdocs\__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\mkdocs\commands\serve.py", line 83, in serve
    builder(config)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\mkdocs\commands\serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\mkdocs\commands\build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\mkdocs\commands\build.py", line 181, in _populate_page
    page.render(config, files)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\mkdocs\structure\pages.py", line 270, in render
    self.content = md.convert(self.markdown)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\markdown\core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\mkdocstrings\extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\mkdocstrings\extension.py", line 193, in _process_block
    data: CollectorItem = handler.collect(identifier, options)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\mkdocstrings_handlers\python\handler.py", line 213, in collect
    loader.load_module(module_name)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\griffe\loader.py", line 145, in load_module
    top_module = self._inspect_module(module)  # type: ignore[arg-type]
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\griffe\loader.py", line 504, in _inspect_module
    module = inspect(
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\griffe\agents\inspector.py", line 88, in inspect
    return Inspector(
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\griffe\agents\inspector.py", line 218, in get_module
    value = dynamic_import(import_path, import_paths)
  File "C:\Users\deguenth\AppData\Local\pypoetry\Cache\virtualenvs\taf-qmYDp-KU-py3.9\lib\site-packages\griffe\importer.py", line 59, in dynamic_import
    module = import_module(module_path)
  File "C:\Program Files\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1027, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _sanity_check
ValueError: Empty module name

**Comment by pawamoy** [comment]
Hello, thanks for the report! Do you have a public repository I could use to replicate the issue and investigate? It is hard to be of any help without a reproducible example.

**Comment by pawamoy** [comment]
You shouldn't add folders that are not part of your package in the `:::` paths.
Could you read [Finding modules](https://mkdocstrings.github.io/python/usage/#finding-modules) and let me know if that solves your issue?

**Comment by pawamoy** [comment]
Closing for lack of information.
